services:
  wordpress:
    build:
      context: brands/bizoholic/cms
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - WP_ENV=production
      - DB_NAME=$DB_NAME
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=wp_db
      - WP_HOME=https://cms.bizoholic.net
      - WP_SITEURL=https://cms.bizoholic.net/wp
      - AUTH_KEY=${CMS_AUTH_KEY}
      - SECURE_AUTH_KEY=${CMS_SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${CMS_LOGGED_IN_KEY}
      - NONCE_KEY=${CMS_NONCE_KEY}
      - AUTH_SALT=${CMS_AUTH_SALT}
      - SECURE_AUTH_SALT=${CMS_SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${CMS_LOGGED_IN_SALT}
      - NONCE_SALT=${CMS_NONCE_SALT}
    networks:
      - dokploy-network
      - traefik-public
      - default
      - bizoholicwebsite-wordpress-rbtyli
    labels:
      - traefik.enable=true
      - traefik.http.routers.bizoholic-cms-http.rule=Host(`cms.bizoholic.net`)
      - traefik.http.routers.bizoholic-cms-http.entrypoints=web
      - traefik.http.routers.bizoholic-cms-http.middlewares=redirect-to-https
      - traefik.http.routers.bizoholic-cms-https.rule=Host(`cms.bizoholic.net`)
      - traefik.http.routers.bizoholic-cms-https.entrypoints=websecure
      - traefik.http.routers.bizoholic-cms-https.tls=true
      - traefik.http.routers.bizoholic-cms-https.tls.certresolver=letsencrypt
      - traefik.http.routers.bizoholic-cms-https.service=bizoholic-cms-v2-svc
      - traefik.http.services.bizoholic-cms-v2-svc.loadbalancer.server.port=80
      - traefik.docker.network=dokploy-network
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    volumes:
      - wp_uploads:/var/www/html/web/app/uploads
    depends_on:
      - wp_db
  wp_db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - wp_data_v3:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    networks:
      - bizoholicwebsite-wordpress-rbtyli
volumes:
  wp_data_v3: null
  wp_uploads: null
networks:
  dokploy-network:
    external: true
  traefik-public:
    external: true
  bizoholicwebsite-wordpress-rbtyli:
    name: bizoholicwebsite-wordpress-rbtyli
    external: true
